# Generated by Django 4.2.3 on 2023-08-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('login', models.CharField(max_length=250)),
                ('senha', models.CharField(max_length=250)),
            ],
        ),
    ]
